//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreGoogle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PreGoogle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martine
        ///Jenny
        ///Ida
        ///Henrik
        ///Alf Knutsen
        ///Fridtjov Næss
        ///Kari Næss
        ///Kirsti Lund
        ///Kristian Næss
        ///Unni Knutsen
        ///Ågot Borgen
        ///Alexander Stolp
        ///Anniken Stolp
        ///Berit Stolp
        ///Emilie Stolp
        ///Evy Knutsen
        ///Finn Jansen
        ///Fredrik Nor
        ///Gunnar Knutsen
        ///Helge Nor
        ///Kathrine Stolp
        ///Knut-Petter Nor
        ///Marianne Jansen
        ///Marius Stolp
        ///Nina Nor
        ///Per Byom
        ///Ragnhild Nor
        ///Randi Jansen
        ///Susanne Nor
        ///Tuva Stolp
        ///Øyvind Kaspersen
        ///Alexander Lilleby
        ///Anders Løhre
        ///Anette Bø
        ///Fredrik Elnæs
        ///Geir Luytkis
        ///Hanne
        ///Helle Sofie Engen
        ///Inga N. Ra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeywordsInclusionList {
            get {
                return ResourceManager.GetString("KeywordsInclusionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Næss
        /// Lund
        /// Knutsen.
        /// </summary>
        internal static string TidyKeywordsList {
            get {
                return ResourceManager.GetString("TidyKeywordsList", resourceCulture);
            }
        }
    }
}
